version: '2'

networks:
  lan:

services:

  master:
    image: neo4j:3.3.1
    container_name: core-placeholder
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_ha_serverId=1
      - NEO4J_dbms_mode=HA
      - NEO4J_ha_server = 192.168.3.250:6000
      - NEO4J_ha.cluster_server = 192.168.3.250:5000
      - NEO4J_ha_initialHosts=192.168.3.250:5000,192.168.3.250:5555,192.168.3.250:5001
      - NEO4J_ha_host_coordination=master:5000
#    network_mode:
#      "host"
    ports:
      - "7474:7474"
      - "7687:7687"
      - "5000:5000"
#      - "5555:5555"
#      - "5001:5001"
    restart:
      always

# Use this to make sure master pushes TXs to both slaves, by default it will be only one
#      - NEO4J_ha_tx__push__factor=2

  slave1:
    image: neo4j:3.3.1
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=HA
      - NEO4J_ha_serverId=2
      - NEO4J_ha_server = 192.168.3.250:6000
      - NEO4J_ha.cluster_server = 192.168.3.250:5000
      - NEO4J_ha_initialHosts=192.168.3.250:5000,192.168.3.250:5555,192.168.3.250:5001
      - NEO4J_ha_host_coordination=slave1:5555
      - NEO4J_ha_host_data=slave1:6666
      - NEO4J_ha_slave__only=true
      - NEO4J_ha_pull__interval=5s # Default value is disabled but we want slave to poll master for test
#    network_mode:
#      "host"
    ports:
      - "17474:7474"
      - "17687:7687"
#      - "5000:5000"
      - "5555:5555"
#      - "5001:5001"
    restart:
      always

  slave2:
    image: neo4j:3.3.1
    container_name: read-placeholder
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=HA
      - NEO4J_ha_server__id=3
      - NEO4J_ha_server = 192.168.3.250:6000
      - NEO4J_ha.cluster_server = 192.168.3.250:5000
      - NEO4J_ha_initial__hosts=192.168.3.250:5000,192.168.3.250:5555,192.168.3.250:5001
      - NEO4J_ha_host_coordination=slave2:5001
      - NEO4J_ha_host_data=slave2:6001
      - NEO4J_ha_slave__only=true
      - NEO4J_ha_pull__interval=5s # Default value is disabled but we want slave to poll master for test
#    network_mode:
#      "host"
    ports:
      - "27474:7474"
      - "27687:7687"
#      - "5000:5000"
#      - "5555:5555"
      - "5001:5001"
    restart:
      always
